apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: argocd-mcp
  namespace: argocd-mcp
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: argocd-mcp
  updatePolicy:
    updateMode: 'Off'
